version: '3.8'

services:
  web:
    image: ianklebold/rag-app-api:v1
    ports:
      - "8000:8000"
    env_file:
      - src/.env
    networks:
      - rag-app-net
  frontend:
    image: ianklebold/rag-app-frontend:v1
    ports:
      - "80:5000"
    networks:
      - rag-app-net

networks:
  rag-app-net:
    driver: bridge